name: happy-app
services:
  api:
    container_name: happy-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    networks:
      - happy-app-network
    restart: always

    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
networks:
  happy-app-network:
